# Generated by Django 3.1 on 2020-08-23 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='questions', to='quiz.Answer'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('creator', 'text')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('creator', 'text')},
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('creator', 'name')},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
    ]
