# Generated by Django 3.1 on 2020-08-24 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_auto_20200823_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Time Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date/Time Updated')),
                ('quiz', picklefield.fields.PickledObjectField(editable=False, verbose_name='Quiz')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'default_related_name': 'quizzes',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Time Created'),
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date/Time Updated'),
        ),
        migrations.AddField(
            model_name='answer',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Time Created'),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date/Time Updated'),
        ),
        migrations.AddField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Time Created'),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date/Time Updated'),
        ),
        migrations.AddField(
            model_name='topic',
            name='uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='UUID'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, editable=False, null=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date/Time Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date/Time Updated')),
                ('score', models.FloatField(verbose_name='Score')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_attempts', to='quiz.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Quiz Attempt',
                'verbose_name_plural': 'Quiz Attempts',
                'default_related_name': 'quiz_attempts',
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='quiz.topic', verbose_name=quiz.models.Topic),
        ),
    ]
