# Generated by Django 3.1 on 2020-08-24 14:13

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200824_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='quiz_attempt',
            field=picklefield.fields.PickledObjectField(default={}, editable=False, verbose_name='Quiz Attempt'),
            preserve_default=False,
        ),
    ]
