# Generated by Django 3.1 on 2021-05-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_question_wrong_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='wrong_answers',
            field=models.ManyToManyField(blank=True, related_name='wrong_questions', to='quiz.Answer'),
        ),
    ]
