default:
  services:
    - name: docker:19.03.12-dind

# Setup stages
stages:
    - build

build-docker-angular:
    stage: build
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE/angular:$CI_COMMIT_REF_NAME -f AngularRandomQuizApp/prod.Dockerfile ./AngularRandomQuizApp
        - docker push $CI_REGISTRY_IMAGE/angular:$CI_COMMIT_REF_NAME

build-docker-django:
    stage: build
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $CI_REGISTRY_IMAGE/django:$CI_COMMIT_REF_NAME -f DjangoRandomQuiz/Dockerfile ./DjangoRandomQuiz
        - docker push $CI_REGISTRY_IMAGE/django:$CI_COMMIT_REF_NAME