version: '3'

volumes:
  sql_data:

services:

  angular:
    image: registry.avodaq.com/wkimchan/djangoangularrandomquizapp/angular:master
#    env_file:
#      - .env
    ports:
      - "4200:80"

  django:
    image: registry.avodaq.com/wkimchan/djangoangularrandomquizapp/django:master
#    env_file:
#      - .env
    ports:
      - "9000:8000"
    volumes:
      - /etc/avodaq/randomquiz/.env:/app/config/.env
      
    depends_on:
      - sql

#  Possibly add the following Docker container for Postgres Database:

  sql:
    image: postgres:9.6.13-alpine
    environment:
      POSTGRES_DB: djangodb
      POSTGRES_USER: django
    volumes:
      - sql_data:/var/lib/postgresql/data
    ports:
      # Use a different port from other postgres databases on the same server
      - "5433:5432"

# Add the following line into .env:
#  DATABASE_URL=postgres://django@sql:5433/djangodb
